---
ID: "dffee92b-0441-45a4-9207-67810b72bd46"
Parent: "895e25c4-12b2-4b2c-8233-82f3b79eef53"
Template: "bc71d442-3e4f-46ba-887c-746e54f9bb83"
Path: /sitecore/system/Settings/Services/Rendering Hosts/Default
SharedFields:
- ID: "3121c257-53cf-464a-b736-98b418876057"
  Hint: AppName
  Value: nextjsstarter
- ID: "94470b31-e282-4d8d-bc54-85689efb294c"
  Hint: ServerSideRenderingEngineConfigUrl
  Value: "https://xmc-5zwxqfdwx43rv83dpoc62j-eh-s.sitecore-staging.cloud/api/editing/config"
- ID: "9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4"
  Hint: __Read Only
  Value: 1
- ID: "e32c1801-79b3-4fc1-a9c4-3c6e6c2968ae"
  Hint: ServerSideRenderingEngineApplicationUrl
  Value: "https://xmc-5zwxqfdwx43rv83dpoc62j-eh-s.sitecore-staging.cloud"
- ID: "fc76919b-0d7c-4732-865d-2af795fb38a4"
  Hint: ServerSideRenderingEngineEndpointUrl
  Value: "https://xmc-5zwxqfdwx43rv83dpoc62j-eh-s.sitecore-staging.cloud/api/editing/render"
Languages:
- Language: en
  Versions:
  - Version: 1
- Language: "fr-CA"
  Versions:
  - Version: 1
- Language: "zh-CN"
  Versions:
  - Version: 1
